apiVersion: apps/v1
kind: Deployment
metadata:
  name: telus-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telus-service
  template:
    metadata:
      labels:
        app: telus-service
    spec:
      containers:
        - name: telus-service
          image: shaikh79/user-service1:1.3.7  # Replace with your image
          ports:
            - containerPort: 7878
          env:
            - name: SERVER_PORT
              value: "7878"
            - name: SPRING_DATASOURCE_URL
              value:   # Replace with your DB URL
            - name: SPRING_DATASOURCE_USERNAME
              value:   # Replace with your DB username
            - name: SPRING_DATASOURCE_PASSWORD
              value:   # Replace with your DB password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: 

---
apiVersion: v1
kind: Service
metadata:
  name: telus-service
spec:
  type: ClusterIP  # Internal service type (use LoadBalancer if external exposure is needed)
  selector:
    app: telus-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7878
