# This file contains the deployment and service configuration for user-service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: irfan-service
  labels:
    app: irfan-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irfan-service
  template:
    metadata:
      labels:
        app: irfan-service
    spec:
      containers:
        - name: irfan-service
          image: shaikh79/user-service1:1.3.4
          ports:
            - containerPort: 7878
---
apiVersion: v1
kind: Service
metadata:
  name: irfan-service
spec:
  type: LoadBalancer
  selector:
    app: irfan-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7878
