apiVersion: apps/v1
kind: Deployment
metadata:
  name: telus-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telus-service
  template:
    metadata:
      labels:
        app: telus-service
    spec:
      containers:
        - name: user-service
          image: shaikh79/user-service1:1.3.8
          ports:
            - containerPort: 7878
          env:
            - name: SERVER_PORT
              value: "7878"
---
apiVersion: v1
kind: Service
metadata:
  name: telus-service
spec:
  selector:
    app: telus-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7878
  type: ClusterIP